### ISSUE TITLE
market.placeOrder side : 'buy' error = Invalid payer account

### ISSUE THREAD

**Issue by mirrrorman** [project-serum/serum-ts#144]
Hello , I've got problem with 'placeOrder / side : buy' 
but side : 'sell' is perfectly worked.
How to fix this problem ?
** This is my errors of side : 'buy' **

`Desktop/serum/node_modules/@project-serum/serum/lib/market.js:409`
`                throw new Error('Invalid payer account');`

`Error: Invalid payer account`
`    at Market.makePlaceOrderTransaction (/Users/chain/Desktop/serum/node_modules/@project-serum/serum/lib/market.js:409:23)`
`    at processTicksAndRejections (internal/process/task_queues.js:95:5)`
`    at async Market.placeOrder (/Desktop/serum/node_modules/@project-serum/serum/lib/market.js:236:42)`
`    at async file:///Desktop/serum/old.js:62:1`

This is my config
PAIR : SOL/USDT
`let marketAddress = new PublicKey('HWHvQhFmJB3NUcu1aihKmrKegfVxBEHzwVX6yZCKEsi1');`
`let programAddress = new PublicKey("9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin");`

❌ `await market.placeOrder(connection, {owner,payer,side: 'buy',price: 10,size: 0.1,orderType: 'limit',});`
✅  `await market.placeOrder(connection, {owner,payer,side: 'sell',price: 50,size: 0.1,orderType: 'limit',});`

Thank You

**Comment by yamen** [comment]
When selling SOL/USDT, the `payer` is the base token SOL account which also equals owner account.

When buying SOL/USDT, the payer is the quote token USDT account.

I'd wager you are setting `payer = owner`, which works in the first scenario, but not the second. You need to set `payer = <USDT token account>`.

**Comment by mirrrorman** [comment]
@yamen Thank you so much brother🥺 , solved !!!
