### ISSUE TITLE
Secret key for New Account ('...')

### ISSUE THREAD

**Issue by Gsuz** [project-serum/serum-ts#158]
I'm using Phantom wallet which gives me a 88 character long private key. Adding this key to New Account gives me the error that the size of the private key is wrong.

**Comment by Gsuz** [comment]
So I've dug through the code and apparantly the key size needs to be 64. Where can I see this key?

**Comment by Gsuz** [comment]
I've figured this out myself.

**Comment by Gaserd** [comment]
@Gsuz where did you find the key (because I keep getting the error that my key is too long) or how did you solve your problem?

**Comment by Bluice81** [comment]
@Gsuz 

How did you solve? Do I also have a phantom wallet where can I retrieve the secret key to be entered in the new Account statement? But is it safe to enter the private key like this?
