### ISSUE TITLE
stake-ui: Lockups should show "available for withdrawal" balance when all funds are in a whitelisted program

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/serum-ts#44]
Currently, when transferring locked funds to the registry program, the "available for withdrawal" UI shows zero, which is correct. However, we should show an additional row representing the amount available for withdrawal if the funds were back in the lockup program, i.e., the amount vested.

**Comment by UrsaarDev** [comment]
👋🏻 Good day, mate.
I make the following utilities based on Solidity & Rust with powerful frontend demonstration.
💻Dapps(Swap, Staking, Referral, Farm, Pool, Presale, Reflection, DAO ...)
💻NFT marketplaces (Opensea, Rarible, Metaplex)
💻Backend software
Leave msgs if you are in the demand of me.
