### ISSUE TITLE
stake-ui: Unlock all button

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/serum-ts#46]
Currently, the Lockup page's unlock button allows a user to withdraw/unlock all tokens from a single vesting account. We should add an additional button that does this for all available vesting accounts, automatically, instead of requiring the user to go through each vesting account one by one.

**Comment by UrsaarDev** [comment]
👋🏻 Good day, mate.
I make the following utilities based on Solidity & Rust with powerful frontend demonstration.
💻Dapps(Swap, Staking, Referral, Farm, Pool, Presale, Reflection, DAO ...)
💻NFT marketplaces (Opensea, Rarible, Metaplex)
💻Backend software
Leave msgs if you are in the demand of me.
