### ISSUE TITLE
borsh: OptionLayout should be u32?

### ISSUE THREAD

**Issue by TimonPeng** [project-serum/serum-ts#68]
https://github.com/project-serum/serum-ts/blob/b7e821efe569b33695439f5771354e958f5e536b/packages/borsh/src/index.ts#L112

https://github.com/solana-labs/solana-program-library/blob/6eac7bc33122412a6ab7fa8b84869ca040d3c1cc/token/js/client/token.js#L129

```ts
export const MintLayout: typeof BufferLayout.Structure = BufferLayout.struct([
  BufferLayout.u32('mintAuthorityOption'),
  Layout.publicKey('mintAuthority'),
  Layout.uint64('supply'),
  BufferLayout.u8('decimals'),
  BufferLayout.u8('isInitialized'),
  BufferLayout.u32('freezeAuthorityOption'),
  Layout.publicKey('freezeAuthority'),
]);
```

**Comment by armaniferrante** [comment]
The `freezeAuthorityOption` is a `COption` not a Rust `Option`. See https://github.com/solana-labs/solana-program-library/blob/47d31cc6f2cf74ba05550e7d2dfdeb035df3ce0c/token/program/src/state.rs#L28. 

Closing.
